'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Tags', [{
        name: 'Bakery',
        UserId: 1,
        BusinessId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 6,
        BusinessId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 4,
        BusinessId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Free Wifi',
        UserId: 2,
        BusinessId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Bakery',
        UserId: 2,
        BusinessId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 5,
        BusinessId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 5,
        BusinessId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 4,
        BusinessId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 1,
        BusinessId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 1,
        BusinessId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 3,
        BusinessId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 3,
        BusinessId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 6,
        BusinessId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 3,
        BusinessId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Free Wifi',
        UserId: 3,
        BusinessId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 1,
        BusinessId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 3,
        BusinessId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Bakery',
        UserId: 2,
        BusinessId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 2,
        BusinessId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 5,
        BusinessId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Good For Groups',
        UserId: 2,
        BusinessId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 2,
        BusinessId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 3,
        BusinessId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 4,
        BusinessId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 2,
        BusinessId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Good For Groups',
        UserId: 4,
        BusinessId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 3,
        BusinessId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 1,
        BusinessId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 2,
        BusinessId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 1,
        BusinessId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Good For Groups',
        UserId: 1,
        BusinessId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 6,
        BusinessId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 6,
        BusinessId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Free Wifi',
        UserId: 3,
        BusinessId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 6,
        BusinessId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 3,
        BusinessId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 2,
        BusinessId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 4,
        BusinessId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 5,
        BusinessId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 3,
        BusinessId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Bakery',
        UserId: 2,
        BusinessId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Food',
        UserId: 5,
        BusinessId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 3,
        BusinessId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 2,
        BusinessId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 1,
        BusinessId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Good For Groups',
        UserId: 1,
        BusinessId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 4,
        BusinessId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 4,
        BusinessId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 3,
        BusinessId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 6,
        BusinessId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 5,
        BusinessId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 6,
        BusinessId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 1,
        BusinessId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 1,
        BusinessId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 2,
        BusinessId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Bakery',
        UserId: 6,
        BusinessId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 2,
        BusinessId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 3,
        BusinessId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 1,
        BusinessId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 6,
        BusinessId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Free Wifi',
        UserId: 2,
        BusinessId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 4,
        BusinessId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 1,
        BusinessId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 2,
        BusinessId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 1,
        BusinessId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 6,
        BusinessId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 3,
        BusinessId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 4,
        BusinessId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 1,
        BusinessId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 6,
        BusinessId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 4,
        BusinessId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 3,
        BusinessId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Food',
        UserId: 4,
        BusinessId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Free Wifi',
        UserId: 2,
        BusinessId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 5,
        BusinessId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 6,
        BusinessId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Bakery',
        UserId: 6,
        BusinessId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 1,
        BusinessId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 1,
        BusinessId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 5,
        BusinessId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 4,
        BusinessId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 1,
        BusinessId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 3,
        BusinessId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 4,
        BusinessId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 5,
        BusinessId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Good For Groups',
        UserId: 2,
        BusinessId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 3,
        BusinessId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 6,
        BusinessId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 2,
        BusinessId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 1,
        BusinessId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Good For Groups',
        UserId: 1,
        BusinessId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 6,
        BusinessId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Good For Groups',
        UserId: 2,
        BusinessId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Free Wifi',
        UserId: 1,
        BusinessId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 6,
        BusinessId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 2,
        BusinessId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 4,
        BusinessId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Free Wifi',
        UserId: 6,
        BusinessId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laptop Friendly',
        UserId: 1,
        BusinessId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 3,
        BusinessId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 5,
        BusinessId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 2,
        BusinessId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 4,
        BusinessId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 6,
        BusinessId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 3,
        BusinessId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 2,
        BusinessId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 2,
        BusinessId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 6,
        BusinessId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Quiet',
        UserId: 1,
        BusinessId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 3,
        BusinessId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Food',
        UserId: 4,
        BusinessId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Food',
        UserId: 4,
        BusinessId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Food',
        UserId: 4,
        BusinessId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 3,
        BusinessId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Good For Groups',
        UserId: 4,
        BusinessId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Quiet',
        UserId: 3,
        BusinessId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 2,
        BusinessId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 2,
        BusinessId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 6,
        BusinessId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 5,
        BusinessId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 2,
        BusinessId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 4,
        BusinessId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 1,
        BusinessId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 1,
        BusinessId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 3,
        BusinessId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 1,
        BusinessId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 4,
        BusinessId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Food',
        UserId: 4,
        BusinessId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 3,
        BusinessId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 4,
        BusinessId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 5,
        BusinessId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 6,
        BusinessId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 5,
        BusinessId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 4,
        BusinessId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 4,
        BusinessId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 3,
        BusinessId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 1,
        BusinessId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 6,
        BusinessId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 6,
        BusinessId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Bakery',
        UserId: 5,
        BusinessId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 5,
        BusinessId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 1,
        BusinessId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 3,
        BusinessId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 1,
        BusinessId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 2,
        BusinessId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 1,
        BusinessId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 3,
        BusinessId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 3,
        BusinessId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 2,
        BusinessId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Quiet',
        UserId: 4,
        BusinessId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 2,
        BusinessId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 2,
        BusinessId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 4,
        BusinessId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 2,
        BusinessId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 2,
        BusinessId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 1,
        BusinessId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 1,
        BusinessId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Food',
        UserId: 5,
        BusinessId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 2,
        BusinessId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Food',
        UserId: 1,
        BusinessId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 5,
        BusinessId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 6,
        BusinessId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 6,
        BusinessId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Bakery',
        UserId: 4,
        BusinessId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Food',
        UserId: 6,
        BusinessId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 5,
        BusinessId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 1,
        BusinessId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 2,
        BusinessId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Quiet',
        UserId: 6,
        BusinessId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 3,
        BusinessId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 3,
        BusinessId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 6,
        BusinessId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 6,
        BusinessId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 3,
        BusinessId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 1,
        BusinessId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 5,
        BusinessId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Quiet',
        UserId: 4,
        BusinessId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 6,
        BusinessId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Outlets',
        UserId: 5,
        BusinessId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 3,
        BusinessId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 4,
        BusinessId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 5,
        BusinessId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 4,
        BusinessId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 4,
        BusinessId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Bakery',
        UserId: 6,
        BusinessId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 2,
        BusinessId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 1,
        BusinessId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Close To Skytrain',
        UserId: 4,
        BusinessId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 5,
        BusinessId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 3,
        BusinessId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Friendly',
        UserId: 6,
        BusinessId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Not Busy',
        UserId: 4,
        BusinessId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 2,
        BusinessId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Good For Groups',
        UserId: 3,
        BusinessId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Relaxing Music',
        UserId: 6,
        BusinessId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lively',
        UserId: 2,
        BusinessId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Air-Conditioning',
        UserId: 2,
        BusinessId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Well Lit',
        UserId: 1,
        BusinessId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cheap',
        UserId: 2,
        BusinessId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comfortable Chairs',
        UserId: 6,
        BusinessId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Tags', null, {});
  },
};
// EMPTY FIELD INSERT STILL WORKS, JUST RETURNS NULL
