'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Tags',
      [{
          name: 'well lit',
          UserId: 6,
          BusinessId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'air conditioning',
          UserId: 6,
          BusinessId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 2,
          BusinessId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 5,
          BusinessId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 3,
          BusinessId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 5,
          BusinessId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 1,
          BusinessId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 5,
          BusinessId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 6,
          BusinessId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 2,
          BusinessId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 4,
          BusinessId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 3,
          BusinessId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 5,
          BusinessId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 1,
          BusinessId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'well lit',
          UserId: 6,
          BusinessId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 6,
          BusinessId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 1,
          BusinessId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 3,
          BusinessId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 1,
          BusinessId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 5,
          BusinessId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 4,
          BusinessId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 1,
          BusinessId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 4,
          BusinessId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 1,
          BusinessId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 1,
          BusinessId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 1,
          BusinessId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 6,
          BusinessId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 1,
          BusinessId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 6,
          BusinessId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 3,
          BusinessId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'well lit',
          UserId: 6,
          BusinessId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 4,
          BusinessId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 4,
          BusinessId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'air conditioning',
          UserId: 5,
          BusinessId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 6,
          BusinessId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 1,
          BusinessId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 5,
          BusinessId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 6,
          BusinessId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 1,
          BusinessId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 3,
          BusinessId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 1,
          BusinessId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 3,
          BusinessId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 3,
          BusinessId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 1,
          BusinessId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 2,
          BusinessId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 5,
          BusinessId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 2,
          BusinessId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 2,
          BusinessId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'air conditioning',
          UserId: 4,
          BusinessId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 2,
          BusinessId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 1,
          BusinessId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 4,
          BusinessId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 6,
          BusinessId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 3,
          BusinessId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 2,
          BusinessId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 4,
          BusinessId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 5,
          BusinessId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'air conditioning',
          UserId: 4,
          BusinessId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 1,
          BusinessId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 3,
          BusinessId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 2,
          BusinessId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 5,
          BusinessId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 4,
          BusinessId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 6,
          BusinessId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 4,
          BusinessId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 4,
          BusinessId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 2,
          BusinessId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'well lit',
          UserId: 2,
          BusinessId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 4,
          BusinessId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 3,
          BusinessId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 1,
          BusinessId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 6,
          BusinessId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 6,
          BusinessId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 2,
          BusinessId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 4,
          BusinessId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 6,
          BusinessId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 4,
          BusinessId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 4,
          BusinessId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 6,
          BusinessId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 6,
          BusinessId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 6,
          BusinessId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 2,
          BusinessId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 1,
          BusinessId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 4,
          BusinessId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 6,
          BusinessId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 3,
          BusinessId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 4,
          BusinessId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 5,
          BusinessId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 3,
          BusinessId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 4,
          BusinessId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 1,
          BusinessId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 4,
          BusinessId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'air conditioning',
          UserId: 4,
          BusinessId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 4,
          BusinessId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 5,
          BusinessId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 4,
          BusinessId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 5,
          BusinessId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'air conditioning',
          UserId: 6,
          BusinessId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 4,
          BusinessId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 1,
          BusinessId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 3,
          BusinessId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 2,
          BusinessId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 1,
          BusinessId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 2,
          BusinessId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 6,
          BusinessId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 4,
          BusinessId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 5,
          BusinessId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 3,
          BusinessId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 2,
          BusinessId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 4,
          BusinessId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 5,
          BusinessId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'well lit',
          UserId: 6,
          BusinessId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'air conditioning',
          UserId: 3,
          BusinessId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 3,
          BusinessId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 4,
          BusinessId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 4,
          BusinessId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 3,
          BusinessId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 1,
          BusinessId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 3,
          BusinessId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 6,
          BusinessId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 2,
          BusinessId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'well lit',
          UserId: 2,
          BusinessId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 2,
          BusinessId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 6,
          BusinessId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 6,
          BusinessId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 3,
          BusinessId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 6,
          BusinessId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'air conditioning',
          UserId: 6,
          BusinessId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 4,
          BusinessId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 2,
          BusinessId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 2,
          BusinessId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 4,
          BusinessId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 6,
          BusinessId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 3,
          BusinessId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 5,
          BusinessId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 5,
          BusinessId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 6,
          BusinessId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 4,
          BusinessId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'well lit',
          UserId: 2,
          BusinessId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 3,
          BusinessId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 2,
          BusinessId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 3,
          BusinessId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 6,
          BusinessId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 4,
          BusinessId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 3,
          BusinessId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 1,
          BusinessId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 3,
          BusinessId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 5,
          BusinessId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 6,
          BusinessId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 5,
          BusinessId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 2,
          BusinessId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 6,
          BusinessId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 3,
          BusinessId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 5,
          BusinessId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 4,
          BusinessId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 2,
          BusinessId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 6,
          BusinessId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 2,
          BusinessId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 2,
          BusinessId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'well lit',
          UserId: 5,
          BusinessId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 2,
          BusinessId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 1,
          BusinessId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'outlets',
          UserId: 1,
          BusinessId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 6,
          BusinessId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 5,
          BusinessId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 3,
          BusinessId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 5,
          BusinessId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'well lit',
          UserId: 6,
          BusinessId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 6,
          BusinessId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 2,
          BusinessId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 6,
          BusinessId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 5,
          BusinessId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 5,
          BusinessId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'well lit',
          UserId: 3,
          BusinessId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'lively',
          UserId: 3,
          BusinessId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 3,
          BusinessId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 4,
          BusinessId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 2,
          BusinessId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 6,
          BusinessId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'cheap',
          UserId: 6,
          BusinessId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 6,
          BusinessId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 2,
          BusinessId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'air conditioning',
          UserId: 4,
          BusinessId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'air conditioning',
          UserId: 2,
          BusinessId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'close to skytrain',
          UserId: 2,
          BusinessId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 1,
          BusinessId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'relaxing music',
          UserId: 5,
          BusinessId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 2,
          BusinessId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'good for groups',
          UserId: 6,
          BusinessId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'well lit',
          UserId: 1,
          BusinessId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 2,
          BusinessId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 4,
          BusinessId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 3,
          BusinessId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 6,
          BusinessId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'bakery',
          UserId: 2,
          BusinessId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'friendly',
          UserId: 1,
          BusinessId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'quiet',
          UserId: 3,
          BusinessId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'comfortable chairs',
          UserId: 4,
          BusinessId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'not busy',
          UserId: 6,
          BusinessId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'food',
          UserId: 6,
          BusinessId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Tags', null, {});
  },
};
// EMPTY FIELD INSERT STILL WORKS, JUST RETURNS NULL
